project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "War Sentiment"
  navbar:
    left:
      - href: analysis/report.qmd
        text: Report

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    fig-width: 10
    fig-height: 7
    fig-dpi: 150
